version: '3.2'

services:
  traefik:
    command:
      - --web
      - --docker
      - --docker.swarmmode=true
      - --docker.watch=true
      - --acme
      - --acme.entrypoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.storage=/acme/acme.json
      - --acme.OnHostRule
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
    ports:
      - "443:443"
    volumes:
      - acme-data:/acme
volumes:
  acme-data:
